create table t_Notes
(
	ID 				INT 		NOT NULL AUTO_INCREMENT,
	UserID 			INT 		NOT NULL,
	Description 	NVARCHAR(64) NOT NULL,  
	SortBy 			INT 		NOT NULL DEFAULT 0,
	LastModified 	DATETIME 	NOT NULL DEFAULT NOW(),

	PRIMARY KEY (ID),
	UNIQUE INDEX (UserID, Description),
	#UNIQUE INDEX (UserID, SortBy),
	FOREIGN KEY (UserID) REFERENCES t_Users (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;