create table t_UsersRoles
(	
	ID		INT	NOT NULL AUTO_INCREMENT,
	UserID 	INT	NOT NULL,
	RoleID 	INT	NOT NULL,

	PRIMARY KEY (ID),
    UNIQUE INDEX (UserID, RoleID),
	FOREIGN KEY (RoleID) REFERENCES t_Roles (ID),
	FOREIGN KEY (UserID) REFERENCES t_Users (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
