create table t_Users
(
	ID 				INT				NOT NULL AUTO_INCREMENT,
	Login 			NVARCHAR(32) 	NOT NULL,
	Pswrd 			NVARCHAR(60) 	NOT NULL,
	Email 			NVARCHAR(255)	NOT NULL,
	IsActive 		BIT(1) 			NOT NULL DEFAULT 1,
    LastModified 	DATETIME 		NOT NULL DEFAULT NOW(),

	PRIMARY KEY (ID),
	UNIQUE INDEX (Login)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
